---
- name: Obtain the infrastructure ID by running
  command: 'oc get -o jsonpath="{.status.infrastructureName}{\"\n\"}" infrastructure cluster'
  register: infra_id

- debug:
    msg: "{{ infra_id.stdout }}"

- set_fact:
    infrastructure_id: "{{ infra_id.stdout }}"
    machineautoscaler_name: "{{ infra_id.stdout }}-{{ role }}-machineautoscaler"
    machineautoscaler_filename: "{{ infra_id.stdout }}-{{ role }}-machineautoscaler.yml"

- name: Create "{{ yaml_directory_name }}"
  file:
    path: "{{ yaml_directory_name }}"
    state: directory

- name: Create MachineAutoScaler File - "{{ yaml_directory_name }}/{{ machineautoscaler_filename }}"
  template:
    src: machineautoscaler.yml.j2
    dest: "{{ yaml_directory_name }}/{{ machineautoscaler_filename }}"
