---
- name: Obtain the infrastructure ID by running
  command: 'oc get -o jsonpath="{.status.infrastructureName}{\"\n\"}" infrastructure cluster'
  register: infra_id

- debug:
    msg: "{{ infra_id.stdout }}"

- set_fact:
    infrastructure_id: "{{ infra_id.stdout }}"

    clusterautoscaler_name: "{{ infra_id.stdout }}-{{ role }}-clusterautoscaler"
    clusterautoscaler_filename: "{{ infra_id.stdout }}-{{ role }}-clusterautoscaler.yml"

- name: Create "{{ yaml_directory_name }}"
  file:
    path: "{{ yaml_directory_name }}"
    state: directory

- name: Create ClusterAutoScaler File - "{{ yaml_directory_name }}/{{ clusterautoscaler_filename }}"
  template:
    src: clusterautoscaler.yml.j2
    dest: "{{ yaml_directory_name }}/{{ clusterautoscaler_filename }}"